name: Copy Files from Another Repo

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch folder from external repo
        run: |
          mkdir -p termux-x11/src/main
          git clone --depth=1 --filter=blob:none --sparse https://github.com/jiaxinchen-max/termux-app temprepo
          cd temprepo
          git sparse-checkout set termux-x11/src/main/cpp
          cp -r termux-x11/src/main/cpp ../termux-x11/src/main/
          cd ..
          rm -rf temprepo

      - name: Commit and push changes
        run: |
         git config user.name "github-actions"
         git config user.email "github-actions@github.com"
         git add termux-x11/src/main/cpp
         if git diff --cached --quiet; then
          echo "✅ No changes to commit"
         else
         git commit -m "Update cpp folder from external repo"
         git push
         fi
