name: Init & Push Submodules

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  push-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git identity and remote
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Pull with rebase
        run: |
          git fetch origin
          git checkout main
          git branch --set-upstream-to=origin/main main
          git pull --rebase origin main

      - name: Init submodules and prepare folders
        run: |
          git submodule update --init --recursive
          mkdir -p termux-x11/src/main/cpp

      - name: Stage, commit and push if needed
        run: |
          git add termux-x11/src/main/cpp || true
          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
          else
            git commit -m "Auto: Add submodule commit references"
            git push origin main
          fi
