name: Copy Files from Another Repo

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull with rebase (force clean)
        run: |
         
         git clean -fdx                # Remove all untracked files/folders, including ignored ones
         git fetch origin
         git checkout main
         git branch --set-upstream-to=origin/main main
         git reset --hard              # Discard all local changes (like gradlew.bat)
         git pull --rebase origin main
      
      
      - name: Fetch folder from external repo
        run: |
          ls
          mkdir -p termux-x11/src/main
          git clone -b master-x11-submodule https://github.com/jiaxinchen-max/termux-app temprepo
          #git clone --depth=1 --filter=blob:none --sparse https://github.com/jiaxinchen-max/termux-app temprepo
          
          cd temprepo
          git sparse-checkout set termux-x11/src/main/cpp
          ls termux-x11/src/main/cpp
          cp -r termux-x11/src/main/cpp ../termux-x11/src/main/
          cd ..
          rm -rf temprepo

      - name: Commit and push changes
        run: |
         git config user.name "github-actions"
         git config user.email "github-actions@github.com"
         git add termux-x11/src/main/cpp
         
         git commit -m "Update cpp folder from external repo"
         git push
         
