name: Init & Push Submodules

on:
  workflow_dispatch:

jobs:
  push-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update and commit submodules
        run: |
          mkdir -p termux-x11/src/main/cpp
          git submodule update --init --recursive
          git add termux-x11/src/main/cpp/*
          git diff --cached --quiet || git commit -m "Auto: Add submodule commit references"

      - name: Push changes
        run: git push
