name: Init & Push Submodules

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  push-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Commit submodule references
        run: |
          git pull
          git add termux-x11/src/main/cpp
          git pull --rebase origin main || true
          git commit -m "Auto: Add submodule commit references"
          git push origin main
         
