name: Upload XoDos Release

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag full (5.1.0.r1)'
        required: true
        default: '5.1.0.r1'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ github.event.inputs.version_tag }}
          git push origin ${{ github.event.inputs.version_tag }}

      - name: Download APK (Google Drive)
        run: |
          pip install gdown
          gdown "13SiZvv2qd1WIdeS-t0C_MzdP78OpAR3w" -O XoDos-${{ github.event.inputs.version_tag }}.apk

      
      - name: Verify APK
        run: |
          ls -lh *.apk
          file *.apk

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version_tag }}
          files: XoDos-${{ github.event.inputs.version_tag }}.apk
