name: Upload XoDos Release

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag (5.1.full)'
        required: true
        default: '5.1.0.full'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ github.event.inputs.version_tag }}
          git push origin ${{ github.event.inputs.version_tag }}

      - name: Download Main APK (Verified Working Method)
        run: |
          pip install gdown --quiet
          gdown "13SiZvv2qd1WIdeS-t0C_MzdP78OpAR3w" -O XoDos-${{ github.event.inputs.version_tag }}-full_arm64-v8a.apk
          
          # Add verification
          if [ ! -f XoDos-${{ github.event.inputs.version_tag }}-full_arm64-v8a.apk ]; then
            echo "APK download failed!"
            exit 1
          fi
          echo "APK size: $(du -sh XoDos-${{ github.event.inputs.version_tag }}-full_arm64-v8a.apk)"

      - name: Download Additional File
        run: |
          gdown "1-3RccaqhYtdAAgvQ4cNGKvOyfp6jP_be" -O XoDos-debian.tar.xz || exit 1
          echo "Additional file size: $(du -sh XoDos-debian.tar.xz)"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version_tag }}
          files: |
            XoDos-${{ github.event.inputs.version_tag }}-full_arm64-v8a.apk
            XoDos-debian.tar.xz
          body: |
            New XoDos release for arm64

**What is new?**
            - Changed and fixed UI
            - Added More features for easier usage
             - added full system data 
             -  added new Glibc drivers and DXVk 
             - added new Bionic Wine 10.0 with new drivers and box64
             - changed and fixed settings app
             - added Mangohud for both Bionic and Glibc
             - added direct game play to open games right from android file picker with wine
            - Added information about android device in terminal
            - And More

download the full version APK (1.6 GB) with Bionic and Glibc wine pre-installed and Linux desktop

**Credits:**
            Team: @Xodios🇾🇪 & @DevArys🇨🇴 & @Mondo_Lambert🇲🇫 & @Aurora0y🇧🇷 & @Chest1902🇧🇩 & jiaxinchen 🇨🇳 & @Snap888🇷🇺
            Logo designer: @xl_v6/ashen🇮🇶
XBox Port:@George-Seven

**Support:**
            Telegram: https://t.me/xodemulatorr
            Discord: https://discord.gg/d2ChVhPfnF
